---
title: "Progress report 1"
author: "Gracie Goheen"
date: "`r Sys.Date()`"
output: 
  github_document:
    toc: true
---

```{r include = FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## New Project Report - Austrailian Wildfires

I will explore the TidyTuesday dataset, depciting the recent [Austrailian wildfires](https://github.com/rfordatascience/tidytuesday/blob/master/data/2020/2020-01-07/readme.md). I will conduct EDA and create visualizations to increase climeate change awareness. As a team challenge, I will have students plot the fires and create a heat map.

I will be looking at example data visualizations from the [New York Times](https://www.nytimes.com/interactive/2020/01/02/climate/australia-fires-map.html) and [BBC News](https://www.bbc.com/news/world-australia-50951043). 

### Data

I will be exploring fire, temperature, and rainfall data.

### Timeline

* Progress report 1 (week 4): import the date, make it tidy, and begin EDA on the temperature data set

* Progress report 2 (week 6): complete EDA on all data sets, devolp visualizations

* Challenge for rest of the team (week 7): develop my plotting challenge (heat map)

* Final report (week 9): compile my findings and craft a report 

### Progress

I have read in some of my data files through Rscripts (mainly temperature and rainfall). I'm still struggling to understand / read the actual fire data. Especailly having difficultties with geom_sf. I have begun EDA on the temperature data and attempted to recreate a graph from the New York Times (see temperature.Rmd). Some of my data appears different and I'm sturggling to understand why. I also worked to understand how to create heat map of Austrailia (like the one from the BBC article), but couldn't figure out how to do it (see fire_heat.Rmd). I wish I had completed more EDA, but I spent a lot of time trying to make my earlier idea work before switching to this data set. However, I am excited because I think this data set will allow me to develop some exciting skills!
