---
title: "Project proposal 2"
author: "Gracie Goheen"
date: "`r Sys.Date()`"
output: 
  github_document:
    toc: true
---

```{r include = FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Idea #1 - A Choose-Your-Own-Adventure Immersive Theatrical Experience

I am currently serving as both the Playwright and Artistic Director of _All the Difference_, an original play that follows four college students over a single night in an Airbnb, drawn together in the aftermath of a horrific incident. The show combines technology and audience participation with traditional playmaking elements for a unique choose-your-own adventure experience that’s different every night. Facilitated by a custom-designed app, the nineteen-person audience must make 6 decisions throughout the play, and each one dramatically changes the story that’s played out on stage. The decisions range from seemingly arbitrary to morally ambiguous to purposefully misleading. This play focuses, both thematically and structurally, on the decisions we make and the consequences that they have on others’ lives. Audiences are forced to confront the decisions they make (individually and collectively) for the characters on stage. A collision of theater and technology, _All the Difference_ uniquely explores the implication of choice and the human desire for chaos. 

I want to go through EDA, and develop visualization tools for the audience-related data collected throughout the fifteen-show run. Data collection and analysis would allow me to gain deep insights into how audiences interact with performance. I want to build creative (potentially interactive) data visualizations to later email to the audience members, so that they can refelct on the decisions that they made during the show.  

The data will be obtained through the app during the run of the show. Each audience member creates a "user profile," where they answer questions such as their age, gender, sexuality, political affiliation, and relious beliefs, as well as other bizarre "would you rather" questions (a total of 22 different variables). I will connect this profile data to the 6 decisions they make during the performance. I will develop analysis for individuals, performance nights, and the entire run. During my analysis I hope to dig into trends based on audience demographics and potentially create models to understand how individuals make decisions / predict future decisions. I also want to understand which pathways are the least visited, so that I can improve my play during further workshops. The data would likely look similar to the data Netflix collected from viewers during [_Bandersnatch_](https://www.denofgeek.com/us/279296/black-mirror-netflix-collected-bandersnatch-data), though mine would also have the added benefit of being attached to an invidual user profile.

For my team challenge, I will select one of the trends and have the team come up with a creative visualization that is both insightful and easy to understand. 

* Progress report 1 (week 4): import my collected data, make it tidy, and create tibbles for my dataframe(s)

* Progress report 2 (week 6): complete EDA to find trends and engaging devlop visualiztions

* Challenge for rest of the team (week 7): select a trend and create a visualiztion challenge

* Final report (week 9): compile my findings and craft a report to share with audience members and the class

## Idea #2 - Austrailian Wildfires

I will explore the TidyTuesday dataset, depciting the recent [Austrailian wildfires](https://github.com/rfordatascience/tidytuesday/blob/master/data/2020/2020-01-07/readme.md). I will conduct EDA and create visualizations to increase climeate change awareness. As a team challenge, I will have students plot the fires and create a heat map.


* Progress report 1 (week 4): import the date, make it tidy, and create tibbles for my dataframe(s)

* Progress report 2 (week 6): complete EDA to find trends and engaging devlop visualiztions

* Challenge for rest of the team (week 7): develop my plotting challenge (heat map)

* Final report (week 9): compile my findings and craft a report 

